test_that("areUnitsIdentical works", {
  # error if not exactly two vectors given
  expect_error(areUnitsIdentical("%", "percent", "FE/yr"))
  # does the function work as intended on examples?
  expect_true(areUnitsIdentical("%", "percent"))
  expect_true(all(areUnitsIdentical("%", c("percent", "Percent"))))
  expect_true(all(areUnitsIdentical(c("%", "percent"), "Percent")))
  expect_true(areUnitsIdentical("whatever", "whatever"))
  expect_true(all(areUnitsIdentical("US$2023", c("USD_2023", "USD2023", "US_2023", "US2023"))))
  expect_true(all(areUnitsIdentical("US$2023/t CO", c("USD_2023/t CO", "USD2023/t CO", "US_2023/t CO", "US2023/t CO"))))
  expect_true(all(areUnitsIdentical("billion USD_2010/yr", c("bn US_2010/yr", "billion US$2010/yr"))))
  expect_true(areUnitsIdentical("EUR2023", "EUR_2023"))
  expect_true(areUnitsIdentical("billion EUR2023/t CO2", "bn EUR_2023/t CO2"))
  expect_true(areUnitsIdentical("billion m2/yr", "bn m2/year"))
  expect_true(areUnitsIdentical("billion pkm/yr", "bn pkm/year"))
  expect_true(areUnitsIdentical("Mt/yr", "Mt/year"))
  expect_true(areUnitsIdentical("Mt CO2-equiv/Mt", "Mt CO2/Mt"))
  expect_true(areUnitsIdentical("tDM/cap/yr", "tDM/capita/yr"))
  expect_true(all(areUnitsIdentical(c("Million", "mio", "million"))))
  expect_true(all(areUnitsIdentical(c("Mt CO2-equiv/yr", "Mt CO2eq/yr", "Mt CO2e/yr", "Mt CO2/yr"))))
  expect_true(all(areUnitsIdentical(c("Percentage", "Percent", "percent", "%"))))
  expect_true(all(areUnitsIdentical(c("USD05", "USD2005", "US$05", "US$2005", "USD2005", "USD_2005"))))
  expect_true(all(areUnitsIdentical(c("USD10", "USD2010", "US$10", "US$2010", "USD2010", "USD_2010"))))
  expect_false(areUnitsIdentical("USD__2020", "USD_2020"))
  expect_false(areUnitsIdentical("billion EUR__2030", "billion EUR2030"))
  expect_false(areUnitsIdentical("US$2020", "US$1999"))
  expect_false(areUnitsIdentical("US$2023/t CO2", "US$2023/Mt CO2"))
  expect_false(areUnitsIdentical("%", "FE/yr"))
  expect_false(any(areUnitsIdentical(c("%", "percent"), "FE/yr")))
})
