test_that("areUnitsIdentical works", {
  expect_error(areUnitsIdentical("%"))
  expect_true(areUnitsIdentical("%", "percent"))
  expect_true(all(areUnitsIdentical("%", c("percent", "Percent"))))
  expect_true(all(areUnitsIdentical(c("%", "percent"), "Percent")))
  expect_true(areUnitsIdentical("whatever", "whatever"))
  expect_false(areUnitsIdentical("%", "FE/yr"))
  expect_false(any(areUnitsIdentical(c("%", "percent"), "FE/yr")))
  expect_error(areUnitsIdentical("%", "percent", "FE/yr"))
})
