#' Retrieves latest template for a given project or mapping file
#'
#' @md
#' @author Falk Benke, Oliver Richters
#' @param project name of the project of requested template, or filename of mapping or template
#' @importFrom utils read.csv2
#' @importFrom gms chooseFromList
#' @importFrom magclass unitsplit
#' @export
getTemplate <- function(project = NULL) {
  templates <- templateNames()
  if (is.null(project)) {
    project <- chooseFromList(names(templates), type = "templates",
                              returnBoolean = FALSE, multiple = FALSE)
    if (length(project) == 0) stop("No template selected, abort.")
  }
  if (! file.exists(project)) {
    project <- gsub("\\.csv$", "", gsub("^mapping_template_", "", project))
  }
  filename <- if (project %in% names(templates)) templates[project] else project
  if (file.exists(filename)) {
    data <- read.csv2(filename, header = TRUE, sep = ";", na.strings = list(""), strip.white = TRUE, quote = "")
    if (ncol(data) == 5) {  # is a mapping template generated by generateMappingfile
      if ("Variable" %in% colnames(data) && ! "Unit" %in% colnames(data)) {
        varunit <- magclass::unitsplit(data$Variable)
        data$Variable <- varunit$variable
        data$Unit <- varunit$unit
      }
      if ("piam_variable" %in% colnames(data) && ! "piam_unit" %in% colnames(data)) {
        varunit <- magclass::unitsplit(data$piam_variable)
        data$piam_variable <- varunit$variable
        data$piam_unit <- varunit$unit
      }
    }
    return(data)
  } else {
    stop("Mapping file ", filename, " not found.")
  }
}
